### ISSUE TITLE
Exception handling request to /auth/email/login.json

### ISSUE THREAD

**Issue by trydofor** [trydofor/pro.fessional.wings#134]
``` console
2023-09-27 02:09:15.591 ERROR 45406 --- [  XNIO-1 task-2] io.undertow.request                      : UT005023: Exception handling request to /auth/email/login.json

java.lang.NullPointerException: find null context, must be user or guest
 at pro.fessional.wings.slardar.context.TerminalContext.get(TerminalContext.java:171) ~[slardar-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.slardar.context.TerminalContext.get(TerminalContext.java:153) ~[slardar-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.slardar.context.TerminalContextAware.getTerminalContext(TerminalContextAware.java:16) ~[slardar-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.warlock.service.user.impl.WarlockUserLoginServiceImpl.auth(WarlockUserLoginServiceImpl.java:66) ~[warlock-bond-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.warlock.service.auth.impl.DefaultDaoAuthnCombo.lambda$onFailure$1(DefaultDaoAuthnCombo.java:191) ~[warlock-bond-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.faceless.service.journal.JournalService.lambda$commit$2(JournalService.java:260) ~[faceless-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.faceless.service.journal.impl.DefaultJournalService.submit(DefaultJournalService.java:55) ~[faceless-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.faceless.service.journal.JournalService.submit(JournalService.java:244) ~[faceless-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.faceless.service.journal.JournalService.commit(JournalService.java:259) ~[faceless-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at pro.fessional.wings.faceless.service.journal.JournalService.commit(JournalService.java:291) ~[faceless-3.0.9.300-20230925.085722-6.jar:3.0.9.300-SNAPSHOT]
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
 at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
 at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.11.jar:6.0.11]
```

**Comment by trydofor** [comment]
TerminalContext normally set/unset in `HandlerInterceptor`.
NOT In Auth filter.

so set/unset in `AuthenticationEventPublisher`
