### ISSUE TITLE
StackOverflowError endless loop

### ISSUE THREAD

**Issue by trydofor** [trydofor/pro.fessional.wings#158]
HeaderWriterFilter$HeaderWriterRequestDispatcher.forward(HeaderWriterFilter.java:170)
LoginUrlAuthenticationEntryPoint.commence(LoginUrlAuthenticationEntryPoint.java:140)

**Comment by trydofor** [comment]
#138 

avoid manual misconfig, add checking code at boot

**Comment by trydofor** [comment]
to avoid manual misconfig, check config at boot

**Comment by trydofor** [comment]
```log
at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper$SessionCommittingRequestDispatcher.forward(SessionRepositoryFilter.java:407) ~[spring-ses
e-3.2.4.jar!/:3.2.4]
at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequestDispatcher.forward(HeaderWriterFilter.java:170) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint.commence(LoginUrlAuthenticationEntryPoint.java:140) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.authentication.DelegatingAuthenticationEntryPoint.commence(DelegatingAuthenticationEntryPoint.java:89) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.access.ExceptionTranslationFilter.sendStartAuthentication(ExceptionTranslationFilter.java:219) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.access.ExceptionTranslationFilter.handleAuthenticationException(ExceptionTranslationFilter.java:185) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:175) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:147) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:91) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.2.5.jar!/:6.2.5]
at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.2.5.jar!/:6.2.5
]
```
